version: '3.8'

services:
  db:
    image: mysql
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: gik-hub
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_network
    healthcheck:
      test:
        [
            "CMD-SHELL",
            "nc -z localhost 3306",
        ]
      interval: 10s
      timeout: 10s
      retries: 10

  nextjs:
    image: node:20
    container_name: nextjs_app
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
    networks:
      - my_network

  migrate:
    image: node:20
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "npm install && npx sequelize-cli db:migrate"
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
    depends_on:
      - db
    networks:
      - my_network
      
networks:
  my_network:
    driver: bridge

volumes:
  mysql_data:
